### ISSUE TITLE
When I attempt to run: ./ovs-toolbox.py; I get "This application failed to start..." with a couple of errors related to qt.qpa.xcb

### ISSUE THREAD

**Issue by dkupper76** [nbonnand/ovs-toolbox#4]
Hello,

Do you think you might be able to help me figure out if I have done something incorrectly or if there is an actual issue?

I am trying to run ovs-toolbox on CentOS 7, and I think I followed the directions properly from the install directions at https://github.com/nbonnand/ovs-toolbox/blob/master/INSTALL

More specifically, it looks like I am running the following versions after installing it:

- CentOS Linux release 7.8.2003 (Core)
- python3.6 / python3.6m and python 2.7
- PyQt5 python3.6/site-packages (5.15.2) and python3.6/site-packages (from PyQt5) (12.8.1)
- paramiko python3.6/site-packages (from paramiko) (1.4.0) and python3.6/site-packages (from paramiko) (3.2.0) and (3.2.1)

When I attempt to run the Python Script ending in .py that is:

"./ovs-toolbox.py" at the Linux Command Line Prompt: # ./ovs-toolbox.py

I get the following errors/outputs:

]# ./ovs-toolbox.py
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
]#

Looking through Google, I am finding a decent amount of results, but I am not sure how relevant they are.  What exactly is it asking to re-install, "Python, the ovs-toolbox, qt.qpa.xcb," or what? I attempted to re-install the python from sudo yum reinstall ..., and I re-downloaded and re-ran the shell to install the toolbox.

Do you have any ideas on how I might get this fixed?

I greatly appreciate any help that you can provide.

Thanks in advance,

**Comment by nbonnand** [comment]
Hello,

What about the simple python/Qt test scripts hello_world01.py and hello_world02.py  ?

( https://github.com/nbonnand/ovs-toolbox/tree/master/test )

Can you run them ? Do they display "Hello World" ?

Regards

Nicolas

**Comment by dkupper76** [comment]
Hi Nicolas,

I greatly appreciate your quick reply and help.  I first had to reinstall the ovs-toolbox to get the test files added, because when I tried to run it, the file was not found, but then I checked your repository and saw that it looks like you added them or changed them or something.  Anyways, after re-installing, I attempted to run both the ovs-toolbox again and the test scripts, and here below are the outputs that I received:

centos178 ovs-toolbox]# ./ovs-toolbox.py
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
centos178 ovs-toolbox]# cd /test
bash: cd: /test: No such file or directory
centos178 ovs-toolbox]# cd test
centos178 test]# ll
total 12
-rw-r--r-- 1 root root  157 Dec  1 07:44 hello_world01.py
-rw-r--r-- 1 root root 1667 Dec  1 07:44 hello_world02.py
-rw-r--r-- 1 root root  185 Dec  1 07:44 README.txt
centos178 test]# ./hello_world01.py
bash: ./hello_world01.py: Permission denied
centos178 test]# sudo chmod +x hello_world01.py
centos178 test]# ./hello_world01.py
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
centos178 test]# sudo chmod +x hello_world02.py
centos178 test]# ./hello_world02.py
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
centos178 test]# 

Will you please let me know what I should try next?

Again, I greatly appreciate your help.

Thanks again,

Daryl

**Comment by nbonnand** [comment]
Hello,

Yes I added the hello_world* files after you submitted this issue so that you could test.
Some ideas:

1) Can you run graphical applications on centos178 ? Like firefox for exemple ?

2) How are you connected to this centos178 ? Are you directly connected to its local console or are you remotely connected to it through ssh or another remote command ? ( In the later case, did you export the DISPLAY from centos178 to your local host ? Does your local host has an X server running ?)

3) I see in some thread (https://forum.qt.io/topic/111553/solved-qt-qpa-plugin-could-not-find-the-qt-platform-plugin-xcb-in/8)  that sometimes people need to specify where is the qt plugins directory location. For example:

export QT_PLUGIN_PATH=/usr/lib/qt/plugins

Your exact QT plugin location might be elsewhere, so you might have to correct the path  /usr/lib/qt/plugins.  For example it could possibly be /usr/lib64/qt5/plugins

So could you please test:
export QT_PLUGIN_PATH=YOUR_REAL_QT_PLUGIN_LOCATION
./hello_world02.py


Regards

Nicolas

**Comment by dkupper76** [comment]
Hello Nicolas,

I appreciate your reply, help, and suggestions.  Here/below are the answers to your questions plus the output of what I get when I run the additional commands:

Yes, I can can run graphical applications on centos178 like Firefox (and I just tested to make sure I still can), by Remote Desktop (RDP) into the Centos Virtual Machine from my Windows 10 Laptop.

I typically don't use the Desktop, but rather SSH

[root@docker-centos178 ovs-toolbox]# cd test
[root@docker-centos178 test]# pwd
/usr/local/bin/ovs-toolbox/test
[root@docker-centos178 test]# ll
total 1856
-rw-r--r-- 1 root root 1886796 Dec  5 22:32 get-pip.py
-rwxr-xr-x 1 root root     157 Dec  1 07:44 hello_world01.py
-rwxr-xr-x 1 root root    1667 Dec  1 07:44 hello_world02.py
-rw-r--r-- 1 root root     185 Dec  1 07:44 README.txt
[root@docker-centos178 test]# export QT_PLUGIN_PATH=YOUR_REAL_QT_PLUGIN_LOCATION
[root@docker-centos178 test]# ./hello_world02.py
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
[root@docker-centos178 test]# 

Do you have any ideas on how to proceed, or what to try next?

Thanks again,

Daryl

**Comment by dkupper76** [comment]
Hi Nicolas,

Not sure what I did different today, or if something updated or what. But I ran the command today, and the OVS-Toolbox Launched on the RDP session to the CentOS server.  So, it looks like it is working.  

Do you have any plans to bring this tool-box to a Web-browser based GUI? Or some sort of external way of reaching it without requiring RDP, another option for GUI would be Electron.JS App, or even some sort of Command Line Based GUI, such as NMTUI or K9s? Just curious.

I am going to work through setting the OVS-Toolbox and testing, but it looks like I got past the errors where it wouldn't open.

I greatly appreciate your help.

Thanks again,

Daryl

**Comment by dkupper76** [comment]
Hi Nicolas,

I am not sure if this is anything significant, however, I ran the commands opened up the OVS-Toolbox, and I just noticed the following error in the Terminal:

SUBPROCESS ERROR text sudo: ovs-vsctl: command not found

Will this affect the operation of this OVS-Toolbox?

Do I need to either re-open or open a new issue? Or is this an easy fix?

Will you please let me know?

Thank you,

Daryl

**Comment by nbonnand** [comment]
Hi Daryl

> Hi Nicolas,
> 
> Not sure what I did different today, or if something updated or what. But I ran the command today, and the OVS-Toolbox Launched on the RDP session to the CentOS server. So, it looks like it is working.

Great !

> Do you have any plans to bring this tool-box to a Web-browser based GUI? Or some sort of external way of reaching it without requiring RDP, another option for GUI would be Electron.JS App,

ovs-toolbox philosophy is the opposite !
- The wrong way to do: install ovs-toolbox where remote openvswitch is (this will force you to remotely access ovs-toolbox ).
- The right way to do: install ovs-toolbox on your local computer and then use ovs-toolbox profiles to manage remote openvswitch through ssh. It is what I describe here: [Multicloud tunneling with Open vSwitch](https://www.youtube.com/watch?v=iG6dIX8edQ0)  I have only one ovs-toolbox on my local PC and I manage 4 remote openvswitches ( one in AWS, one in GCP, one in Azure and one in  OVH cloud )

> or even some sort of Command Line Based GUI
I do not plan to reinvent command line to administrate openvswitch as it already exists !!!
It is called: **ovs-vsctl** and is part of openvswitch package

Regards

Nicolas

**Comment by nbonnand** [comment]
Hi Daryl, 

> Hi Nicolas,
> 
> I am not sure if this is anything significant, however, I ran the commands opened up the OVS-Toolbox, and I just noticed the following error in the Terminal:
> 
> SUBPROCESS ERROR text sudo: ovs-vsctl: command not found
> 
> Will this affect the operation of this OVS-Toolbox?

Definitely !!

ovs-vsctl is part of openvswitch package. Did you install openvswitch ? 
( yum install openvswitch )

Once it is installed, you should be able to query openvswich database:

# ovs-vsctl list-br
# ovs-vsctl show


ovs-toolbox needs ovs-vsctl for nearly every action !!!

I suggest you begin by studying this nice video tutorial introduction about openvswitch by Davis Mahler [Introduction to Open vSwitch (OVS)](https://www.youtube.com/watch?v=rYW7kQRyUvA) 

Regards

Nicolas








> 
> Do I need to either re-open or open a new issue? Or is this an easy fix?
> 
> Will you please let me know?
> 
> Thank you,
> 
> Daryl

**Comment by dkupper76** [comment]
Hi Nicolas,

I greatly appreciate all your help and answers.  I will definitely watch the YouTube video and read the article by David. Yes I had previously installed OpenVSwitch, and I also installed DPDK, as I tried to setup multiple interfaces, and have 2 of them use DPDK, but I had issues getting it to work, and in my research, I stumbled on your git-hub repo for ovs-toolbox, so I thought I would give it a try for management instead of using the ovs commands. So I am not sure if something I done along the way broke the openVSwitch. I will keep trying to figure it out, hopefully I am just missing something easy.

Thanks again,

Daryl

**Comment by nbonnand** [comment]
> Hi Nicolas,
> 
> I greatly appreciate all your help and answers. I will definitely watch the YouTube video and read the article by David. Yes I had previously installed OpenVSwitch, and I also installed DPDK, as I tried to setup multiple interfaces, and have 2 of them use DPDK, but I had issues getting it to work, and in my research, I stumbled on your git-hub repo for ovs-toolbox, so I thought I would give it a try for management instead of using the ovs commands. So I am not sure if something I done along the way broke the openVSwitch. I will keep trying to figure it out, hopefully I am just missing something easy.
> 
> Thanks again,
> 
> Daryl

Hello,

I have NOT validated ovs-toolbox for DPDK mode.

My assumption is that ovs-toolbox will NOT work in this mode. 
(Or maybe some of its features would work and some others not.)

This is definitely something I should spend time on !

Regards

Nicolas
