### ISSUE TITLE
Transaction Log

### ISSUE THREAD

**Issue by dyvesh** [nbonnand/ovs-toolbox#6]
Hello,

Do you have a transaction logs, which saves all the commend send to the OVS ?
Where we review all the commands and send for potential error?
The same transaction logs can be used as export or import for future projects.

Thank you,
Dheeraaj

**Comment by nbonnand** [comment]
Hello,

Yes there is a transaction log.
Here is how to display it:

[Console/transaction logs](https://github.com/nbonnand/ovs-toolbox/wiki/console_01)

Regards

Nicolas

**Comment by dyvesh** [comment]
Thank you great tools
